# Generated by Django 4.2.1 on 2023-06-30 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='cover')),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='published')),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='pdf document')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(upload_to='', verbose_name='portrait')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.publication'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.section'),
        ),
        migrations.AddField(
            model_name='article',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.signature'),
        ),
    ]
