# Generated by Django 4.2.1 on 2023-06-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='document',
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='portrait',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
