# Generated by Django 4.2.1 on 2023-06-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0002_remove_publication_document_publication_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.section'),
        ),
        migrations.AlterField(
            model_name='article',
            name='signature',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.signature'),
        ),
    ]
