# Generated by Django 4.2.1 on 2023-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0003_alter_article_section_alter_article_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/covers/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(upload_to='uploads/documents/'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='portrait',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/portraits/'),
        ),
    ]
