# Generated by Django 4.2.1 on 2023-07-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0004_alter_publication_cover_alter_publication_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(help_text="Número en que es va publicar l'article", on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.publication', verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, default=None, help_text="Secció on es va publicar l'article. <strong>Opcional</strong>", null=True, on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.section', verbose_name='Secció'),
        ),
        migrations.AlterField(
            model_name='article',
            name='signature',
            field=models.ForeignKey(blank=True, default=None, help_text="Firma de l'autoria de l'article. <strong>Opcional</strong>", null=True, on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.signature', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text="Títol i subtítol si s'escau", max_length=200, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, default='static/hemeroteca/cover-placeholder.png', help_text='Portada del número en format png o jpg. <strong>Opcional</strong>', null=True, upload_to='uploads/covers/', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(help_text='Data en que es va publicar el número', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(help_text='Arxiu PDF amb la publicació', upload_to='uploads/documents/', verbose_name='Document PDF'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.IntegerField(help_text='Numeració serial de les publicacions', primary_key=True, serialize=False, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la secció'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la persona redactora'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='portrait',
            field=models.ImageField(blank=True, default='static/hemeroteca/portrait-placeholder.png', help_text='Imatge en format png o jpg de mida petita. <strong>Opcional</strong>', null=True, upload_to='uploads/portraits/', verbose_name='Foto de perfil'),
        ),
    ]
