# Generated by Django 4.2.1 on 2023-07-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0005_alter_publication_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Contingut', 'verbose_name_plural': 'Continguts'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-number'], 'verbose_name': 'Publicació', 'verbose_name_plural': 'Publicacions'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name'], 'verbose_name': 'Secció', 'verbose_name_plural': 'Seccions'},
        ),
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['name'], 'verbose_name': 'Firma', 'verbose_name_plural': 'Firmes'},
        ),
    ]
