# Generated by Django 4.2.1 on 2023-07-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0006_alter_article_options_alter_content_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.IntegerField(default=1, help_text="Pàgina on apareix l'article", verbose_name='Pàgina'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, default='hemeroteca/cover-placeholder.png', help_text='Portada del número en format png o jpg. <strong>Opcional</strong>', null=True, upload_to='static/hemeroteca/uploads/covers/', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(help_text='Arxiu PDF amb la publicació', upload_to='static/hemeroteca/uploads/documents/', verbose_name='Document PDF'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='portrait',
            field=models.ImageField(blank=True, default='hemeroteca/portrait-placeholder.png', help_text='Imatge en format png o jpg de mida petita. <strong>Opcional</strong>', null=True, upload_to='hemeroteca/uploads/portraits/', verbose_name='Foto de perfil'),
        ),
    ]
