# Generated by Django 4.2.3 on 2023-07-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0007_article_page_alter_publication_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='article',
        ),
        migrations.AddField(
            model_name='content',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hemeroteca.publication'),
            preserve_default=False,
        ),
    ]
