# Generated by Django 4.2.3 on 2023-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0008_remove_content_article_content_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(help_text='Data en que es va publicar el número', verbose_name='Data'),
        ),
    ]
