# Generated by Django 4.2.3 on 2024-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0009_alter_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.IntegerField(default=1, help_text="Pàgina on apareix l'article", verbose_name='Pàgina'),
        ),
    ]
