# Generated by Django 4.2.3 on 2024-02-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0010_content_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_vector',
            field=models.BooleanField(default=True, help_text="L'arxiu font és un PDF de tipus vectorial", verbose_name='PDF vectorial'),
        ),
    ]
