# Generated by Django 5.0.6 on 2024-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0011_publication_is_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='signature',
        ),
        migrations.AddField(
            model_name='article',
            name='signature',
            field=models.ManyToManyField(blank=True, default=None, help_text="Firma de l'autoria de l'article. <strong>Opcional</strong>", null=True, to='hemeroteca.signature', verbose_name='Firma'),
        ),
    ]
