# Generated by Django 5.0.6 on 2024-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0012_remove_article_signature_article_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='signature',
            field=models.ManyToManyField(blank=True, default=None, help_text="Firma de l'autoria de l'article. <strong>Opcional</strong>", to='hemeroteca.signature', verbose_name='Firma'),
        ),
    ]
