# Generated by Django 5.0.6 on 2024-05-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0013_alter_article_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='signature',
            new_name='signatures',
        ),
    ]
